Repository zaranaramorimori/HACKER-iOS, pull requests merged in 2022-03, with the labels that each got.

#16 [ADD] #9 - 코드리뷰 반영
  HACKER/HACKER/Resources/Extensions/UIFont+Extension.swift
  HACKER/HACKER/Resources/Extensions/UITextField+Extension.swift
  HACKER/HACKER/Sources/SceneDelegate.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/LoginViewController.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/SplashViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainProfileViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NickNameCheckPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/UnknownUserPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/SignupViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TabBarViewController/TabBarViewController.swift
Labels: 지수💆🏻‍♀️, ADD

#15 [FEAT] #11 - Signup, Nickname UI 테스트코드 작성
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Info.plist
  HACKER/HACKER/Resources/Constants/TargetIdentifier.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/SignupViewController.swift
  HACKER/HACKERTests/HACKERTests.swift
  HACKER/HACKERUITests/HACKERUITests.swift
  HACKER/HACKERUITests/NicknameUITests.swift
  HACKER/HACKERUITests/SignupUITests.swift
  HACKER/HACKERUITests/Utils/TestErrorMessage.swift
  HACKER/HACKERUITests/Utils/UITestUtils.swift
  HACKER/HACKERUITests/Utils/XCUIApplication+Extension.swift
  HACKER/HACKERUITests/Utils/XCUIElement+Extension.swift
  HACKER/Podfile
  HACKER/Podfile.lock
Labels: FEAT, 다은👨🏻‍🦲

#21 [CHORE] #10 - identifier 변경 후 등록
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/HACKER.entitlements
Labels: 이준👶🏻, CHORE

#19 [FEAT] #13 - 설정 뷰 UI
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Constants/Const.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/Cell/SettingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/SettingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ViewController.swift
  HACKER/HACKER/Sources/Views/HackerNavigationBar.swift
Labels: 이준👶🏻, FEAT
