Repository zaranaramorimori/HACKER-iOS, pull requests merged in 2022-06, with the labels that each got.

#67 [FIX] #64 Apple Login 200,201 Status 분기처리
  HACKER/HACKER.xcodeproj/xcuserdata/kimjisoo.xcuserdatad/xcschemes/xcschememanagement.plist
  HACKER/HACKER/Sources/NetworkService/Login/LoginAPI.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/LoginViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
Labels: 지수💆🏻‍♀️, FIX

#70 [FEAT] #69 - 만든 사람들 웹뷰 연결
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/SettingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/WebkitViewController.swift
Labels: FEAT, 다은👨🏻‍🦲

#71 [FIX] #64 RankingTableVC 닉네임, 커밋 Label Layout 수정
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingTableViewCell.swift
Labels: 지수💆🏻‍♀️, FIX

#74 [FIX] #72 RankingCVC 에서 myRankView 클릭 시 Crash나는 현상해결
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingCollectionViewCell.swift
Labels: 지수💆🏻‍♀️, FIX

#80 [FIX] - #75 UI,Layout 수정
  HACKER/HACKER/Resources/Assets.xcassets/threemanIcon.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/threemanIcon.imageset/threemanIcon.png
  HACKER/HACKER/Resources/Assets.xcassets/threemanIcon.imageset/threemanIcon@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/threemanIcon.imageset/threemanIcon@3x.png
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainProfileViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainViewController.swift
Labels: 지수💆🏻‍♀️, FIX

#81 [FIX] #76 - QA 반영
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Assets.xcassets/addFriend.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/addFriend.imageset/addFriend.png
  HACKER/HACKER/Resources/Assets.xcassets/addFriend.imageset/addFriend@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/addFriend.imageset/addFriend@3x.png
  HACKER/HACKER/Resources/Assets.xcassets/exclamationButton.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/exclamationButton.imageset/exclamationButton.png
  HACKER/HACKER/Resources/Assets.xcassets/exclamationButton.imageset/exclamationButton@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/exclamationButton.imageset/exclamationButton@3x.png
  HACKER/HACKER/Sources/AppDelegate.swift
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/AddFriendViewController.swift
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/CheckAddUserPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/CheckFriendViewController.swift
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/NotHackerUserPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/FriendDetailViewController.swift
Labels: FEAT, FIX, 다은👨🏻‍🦲

#83 [FEAT] #82 - 로딩 뷰 구현
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Class/LoadingHUD.swift
  HACKER/HACKER/Resources/Lottie/lf30_editor_kdpmpt6l.json
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/AddFriendViewController.swift
  HACKER/HACKER/Sources/ViewControllers/AddFriendViewController/CheckAddUserPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightViewController.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/LoginViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/AlarmViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainProfileViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/DeleteAccountViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/ShoppingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/FriendDetailViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/ShoppingRankingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/SignupViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/TeamViewController.swift
Labels: FEAT, 다은👨🏻‍🦲
