Repository zaranaramorimori/HACKER-iOS, pull requests merged in 2022-05, with the labels that each got.

#32 [FEAT] #31 - 서버 초기세팅
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Constants/Const.swift
  HACKER/HACKER/Resources/Constants/Header.swift
  HACKER/HACKER/Resources/Constants/URL.swift
  HACKER/HACKER/Resources/Constants/UserDefaultsKey.swift
  HACKER/HACKER/Sources/Models/GenericResponse.swift
  HACKER/HACKER/Sources/Models/NetworkResult.swift
  HACKER/HACKER/Sources/NetworkService/HowTo.swift
Labels: 이준👶🏻, FEAT

#33 [FEAT] #25 - 경쟁 뷰 UI
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Assets.xcassets/fightMainIcon.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/fightMainIcon.imageset/fightMainIcon.png
  HACKER/HACKER/Resources/Assets.xcassets/fightMainIcon.imageset/fightMainIcon@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/fightMainIcon.imageset/fightMainIcon@3x.png
  HACKER/HACKER/Resources/Assets.xcassets/teamCharacterImage.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/teamCharacterImage.imageset/teamCharacterImage.png
  HACKER/HACKER/Resources/Assets.xcassets/teamCharacterImage.imageset/teamCharacterImage@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/teamCharacterImage.imageset/teamCharacterImage@3x.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonActive.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonActive.imageset/yesButton.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonActive.imageset/yesButton@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonActive.imageset/yesButton@3x.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonInactive.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonInactive.imageset/yesButtonInactive.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonInactive.imageset/yesButtonInactive@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/yesButtonInactive.imageset/yesButtonInactive@3x.png
  HACKER/HACKER/Sources/SceneDelegate.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/Cell/FightTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightTableViewHeader.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightViewController.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/SplashViewController.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/Cell/TeamRankingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingTableViewHeader.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/DeleteAccountViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SettingViewController/SettingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TabBarViewController/TabBarViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/Cell/LogTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/Cell/MemberCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/TeamViewController.swift
  HACKER/HACKER/Sources/Views/HackerNavigationBar.swift
Labels: 이준👶🏻, FEAT

#38 [CHORE] #37 - 서버 초기세팅 수정
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Constants/Header.swift
  HACKER/HACKER/Resources/Constants/URL.swift
  HACKER/HACKER/Sources/NetworkService/Fight/FightAPI.swift
  HACKER/HACKER/Sources/NetworkService/Fight/FightService.swift
  HACKER/HACKER/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/DataModel/SeasonResponse.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightViewController.swift
Labels: 이준👶🏻, CHORE

#39 [FEAT] - #29 깃허브 유저네임VC, 닉네임VC 서버연결 완료
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Extensions/UIViewController+Extension.swift
  HACKER/HACKER/Sources/NetworkService/NickName/NickNameAPI.swift
  HACKER/HACKER/Sources/NetworkService/NickName/NickNameService.swift
  HACKER/HACKER/Sources/NetworkService/SignUp/SignUpAPI.swift
  HACKER/HACKER/Sources/NetworkService/SignUp/SignUpService.swift
  HACKER/HACKER/Sources/SceneDelegate.swift
  HACKER/HACKER/Sources/ViewControllers/LoginViewController/LoginViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/DataModel/NickNameRequest.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/DataModel/NickNameResponse.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NickNameCheckPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/DataModel/SignUpResponse.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/SignupPopUpViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/SignupViewController.swift
  HACKER/HACKER/Sources/ViewControllers/SignupViewController/UnknownUserPopUpViewController.swift
Labels: 지수💆🏻‍♀️, FEAT

#41 [FEAT] #34 - 경쟁 뷰 서버연결
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Assets.xcassets/emptyLogo.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/emptyLogo.imageset/logo100.png
  HACKER/HACKER/Resources/Assets.xcassets/emptyLogo.imageset/logo100@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/emptyLogo.imageset/logo100@3x.png
  HACKER/HACKER/Resources/Extensions/UIImageView+Extension.swift
  HACKER/HACKER/Sources/NetworkService/Fight/FightAPI.swift
  HACKER/HACKER/Sources/NetworkService/Fight/FightService.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/Cell/FightTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/DataModel/SeasonTeamResponse.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightViewController.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/Cell/TeamRankingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/DataModel/TeamDetailResponse.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/TeamViewController.swift
  HACKER/HACKER/Sources/Views/EmptyView.swift
Labels: 이준👶🏻, FEAT

#42 [CHORE] #36 - 앱 아이콘 추가
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/120-1.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  HACKER/HACKER/Resources/Lottie/pulledOut.json
  HACKER/HACKER/Resources/Lottie/pullingOut.json
  HACKER/HACKER/Sources/SceneDelegate.swift
Labels: 이준👶🏻, CHORE

#44 [FEAT] - #40 MainVC, MainDetail VC 서버 연결
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Sources/NetworkService/Main/MainAPI.swift
  HACKER/HACKER/Sources/NetworkService/Main/MainService.swift
  HACKER/HACKER/Sources/SceneDelegate.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainDataModel/MainDetailResponse.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainDataModel/MainResponse.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainProfileViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainViewController.swift
  HACKER/HACKER/Sources/ViewControllers/NicknameViewController/NicknameViewController.swift
Labels: 지수💆🏻‍♀️, FEAT

#58 [FEAT] - #48 RankingVC, ShoppingVC 서버 연결 완료
  HACKER/HACKER.xcodeproj/project.pbxproj
  HACKER/HACKER/Sources/NetworkService/SearchFriend/SearchFriendAPI.swift
  HACKER/HACKER/Sources/NetworkService/SearchFriend/SearchFriendService.swift
  HACKER/HACKER/Sources/NetworkService/TotalRanking/RankingAPI.swift
  HACKER/HACKER/Sources/NetworkService/TotalRanking/RankingService.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/MyFriendsCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/ShoppingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/DataModel/RankingResponse.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/DataModel/SearchFriendResponse.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/FriendDetailViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/ShoppingRankingViewController.swift
Labels: 지수💆🏻‍♀️, FEAT

#61 [FEAT] #48 - MainVC Commit 관련 분기처리
  HACKER/HACKER.xcodeproj/xcuserdata/kimjisoo.xcuserdatad/xcschemes/xcschememanagement.plist
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainDataModel/MainDetailResponse.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainDataModel/MainResponse.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainProfileViewController.swift
  HACKER/HACKER/Sources/ViewControllers/MainViewController/MainViewController.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/MyFriendsCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/RankingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/Cells/ShoppingCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/DataModel/RankingResponse.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/DataModel/SearchFriendResponse.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/DataModel/ShoppingResponse.swift
  HACKER/HACKER/Sources/ViewControllers/ShoppingRankingViewController/FriendDetailViewController.swift
Labels: 지수💆🏻‍♀️, FEAT

#65 [FEAT] #55 - 경쟁 뷰 UI 수정, 서버
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  HACKER/HACKER/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/mainHead.imageset/Contents.json
  HACKER/HACKER/Resources/Assets.xcassets/mainHead.imageset/mainHead.png
  HACKER/HACKER/Resources/Assets.xcassets/mainHead.imageset/mainHead@2x.png
  HACKER/HACKER/Resources/Assets.xcassets/mainHead.imageset/mainHead@3x.png
  HACKER/HACKER/Sources/ViewControllers/FightViewController/Cell/FightTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/DataModel/SeasonTeamResponse.swift
  HACKER/HACKER/Sources/ViewControllers/FightViewController/FightViewController.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/Cell/TeamRankingTableViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingTableViewHeader.swift
  HACKER/HACKER/Sources/ViewControllers/RankingViewController/RankingViewController.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/Cell/MemberCollectionViewCell.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/DataModel/TeamDetailResponse.swift
  HACKER/HACKER/Sources/ViewControllers/TeamViewController/TeamViewController.swift
  HACKER/HACKER/Sources/Views/EmptyView.swift
  HACKER/HACKER/Sources/Views/HackerNavigationBar.swift
Labels: 이준👶🏻, FEAT
